powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\aqu-archive.ps1"
powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\bel-archive.ps1"
REM powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\cd-archive.ps1"
powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\dmr-archive.ps1"
powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\fg-archive.ps1"
REM powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\kee-archive.ps1"
powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\op-archive.ps1"
powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\sa-archive.ps1"
REM powershell "D:\HostingSpaces\admin\bioappeng.us\data\WS\processed\archive\sar-archive.ps1"
